version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: rsoi_persons_6qmq_user
      POSTGRES_PASSWORD: "WXXjkvg7vd3q1AE4ycIoTIOS9tlq7s8V"
      POSTGRES_DB: rsoi_persons_6qmq
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

volumes:
  db-data:
